Quest 3 1
yogadeveloper/Reactpub pull request #7
Opened 2020-10-04 09:31 UTC by yogadeveloper

2020-10-05 10:53 UTC, index01d requested changes

2020-10-05 10:53 UTC, index01d commented on src/components/AddToCart.js
> +      { title: 'Minimum Price', value: <Price value={minPrice} /> },
Не стоит определять React-элементы вне return, а также плохой практикой является передача элементов с помощью свойств (это справедливо не всегда, но в большинстве случаев).

С помощью свойств можно передавать данные, опции и функции. Передача внутри свойств React-элементов указвает на проблемы при проектировании (так как усложняется понимание иерархии компонентов интерфейса).

2020-10-05 10:53 UTC, index01d commented on src/components/BookCard.js
>    toggleModal(e) {
является частью реализации модального окна, следует выделить соответствующий компонент.

2020-10-05 10:53 UTC, index01d commented on src/components/BookCard.js
>      this.state = { modalIsActive: false }
вряд ли это состояние относитсяк карточке книги, см ниже.

2020-10-05 10:53 UTC, index01d commented on src/components/BookCardCover.js
> +          <img src={this.props.coverUrl} alt={this.propstitle} />
похоже в alt опечатка `propstitle`

2020-10-05 10:53 UTC, index01d commented on src/components/BookCardPricing.js
> +class BookCardPricing extends React.Component {
чтобы избавиться от избыточности в именах можно сгруппировать компоненты в директорию
```
BookCard/
  Pricing.js -- частный компонент
  Price.js
  ...
  index.js -- главный компонент карточки
```

2020-10-05 10:53 UTC, index01d commented on src/components/BookCardPricing.js
> +                key={`price-${i}`}
ключу необязательно быть уникальным в рамках всей иерархии, достаточно быть уникальным в рамках текущего массива: `key={i}` в данном случае тоже годится

2020-10-05 10:53 UTC, index01d commented on src/components/BookCardPricing.js
> +              <BookCardPrice
если этот компонент не реиспользуется без Pricing, то стоит определить его здесь же ниже, чтобы не усложнять навигацию.

2020-10-05 10:53 UTC, index01d commented on src/components/BookCardSummary.js
> +  renderTitle(title) {
как писал выше, определять функцию, возвращающую JSX вне render+return компонента не лучшая практика: обычно это указывает на необходимость выделить компонент. Например здесь сложно прочитать, что происходит

```
  {followers >= 10000 ? <TitleWithIcon>{title}</TitleWithIcon> : <Title>{title}</Title>}
```
вполне могло бы поместиться в основной render и лучше бы отражало происходящее

2020-10-05 10:53 UTC, index01d commented on src/components/BookCardSummary.js
> +  renderBookAuthors() {
аналогично можно разбить на компоненты

2020-10-05 10:53 UTC, index01d commented on src/components/ContactForm.js
> +    switch (event.target.type) {
лучше ориентироваться на name:
```
setState({
  [e.target.name]: e.target.value
})
```

иначе будет проблема, когда добавится ещё одно поле textarea

2020-10-05 10:53 UTC, index01d commented on src/components/FeaturedBookAuthorContainer.js
> +      <>
выглядит, будто фрагмент лишний

2020-10-05 10:53 UTC, index01d commented on src/components/ProgressBar.js
> +      <>
кажется, что этот блок заслуживает своего div?

2020-10-05 10:53 UTC, index01d commented on src/components/ProgressBar.js
> +    const progress = this.props.progress;
кратче была бы запись с деструктурированием `const { progress } = this.props`

2020-10-05 10:53 UTC, index01d commented on src/components/PromotionBox.js
> +  renderPromotion() {
выделение в функцию не выглядит оправданным

2020-10-05 10:53 UTC, index01d commented on src/components/PromotionBox.js
> +  renderPromotion() {
описывал вариант выше, стоило бы реализовать соответствующие варианты компонентов

2020-10-05 10:53 UTC, index01d commented on src/components/PromotionList.js
> +            return (
можно описать без return

2020-10-05 10:53 UTC, index01d commented on src/components/UserInfo.js
> +            console.log(user);
?

2020-10-05 10:53 UTC, index01d commented on src/components/UserInfo.js
> +    console.log(user.firstName);
?

2020-10-05 10:53 UTC, index01d commented on src/components/UserInfo.js
> +    console.log(user.firstName);
кажется, метод не используется

2020-10-05 10:53 UTC, index01d commented on src/components/FeaturedBookAuthorContainer.js
> +          <AuthorCardList authors={this.props.authors} openContactForm={this.openContactForm} />
желательно заранее деструктурировать поля из this.props и this.state, чтобы сохранять jsx код читабельным и кратким

`const { active, authors, .... } = this.props`

2020-10-05 10:53 UTC, index01d commented on src/components/ContactForm.js
> +          <h3 className='text-h5'>{`Contact ${name}`}</h3>
здесь можно просто 
`<h3 className='text-h5' >Contact {name}</h3>`

JSX-синтаксис будет кратче

2020-10-05 10:53 UTC, index01d commented on src/components/AuthorCard.js
>            <h4 className="author-card__name text-h4">{ fullName(this.props.author) }</h4>
Наверно можно обойтись без helper'a. Он скорее усложняет ситуацию :)

2020-10-05 10:53 UTC, index01d commented on src/components/AddToCart.js
> +                  <RangeSlider min={minPrice} max={suggestedPrice} defaultValue={this.state.rangeSliderValue} callback={this.handlePriceChange} />
Полагаю, callback стоило бы переименовать в onChange, с целью приведения к общепринятой конвенции.

2020-10-05 10:56 UTC, index01d requested changes

2020-10-05 10:56 UTC, index01d commented on src/components/PromotionItem.js
> +      <div className="promotion-item" key={`promo-${promo.title}`}>
Ключ нужно определять для элемента списка, а не в компоненте. см пример в официальной документации
https://reactjs.org/docs/lists-and-keys.html#extracting-components-with-keys

2020-10-08 18:05 UTC, index01d requested changes

2020-10-08 18:05 UTC, index01d commented on src/components/ContactForm.js
>        <>
фрагмент выглядит лишним

2020-10-10 00:38 UTC, yogadeveloper commented on src/components/BookCard.js
>      this.state = { modalIsActive: false }
я переделал Modal с использованием Context, скоро буду отправлять коммит со всеми правками. Скажи пожалуйста, а мне делать resolve conversation здесь только после того как я делаю коммит с правками или для удобства могу их закрывать когда делаю изменения у себя локально?

2020-10-11 10:42 UTC, index01d approved these changes

2020-10-11 10:42 UTC, index01d commented on src/components/BookCard/PriceList.js
> +        })
не вполне понятно зачем деструктурировать на этом этапе.
```
prices.map(
  (price), i) => (
     <BookCardPrice price={price} key={i} /> {/* или <BookCard {...price} key={i} />, когда нет выхода:) */}
  )
)
```

2020-10-11 10:42 UTC, index01d commented on src/components/BookCard/Summary/Authors.js
> +    <>
выглядит будто фрагмент лишний. Можно обойтись без него

2020-10-11 10:42 UTC, index01d commented on src/components/Title.js
> +  className += " display-inline";
стоит использовать https://www.npmjs.com/package/classnames

2020-10-11 10:42 UTC, index01d commented on src/components/Title.js
> +  const { className, tag, children } = props;
```
const { className, tag: Tag, children } = props;
```
см ниже

2020-10-11 10:42 UTC, index01d commented on src/components/Title.js
> +    React.createElement(tag, {className: className}, props.children)
```
<Tag className={className}>{children}</Tag>
```

2020-10-13 04:56 UTC, yogadeveloper commented on src/components/Title.js
> +  const { className, tag, children } = props;
лайфхак :)

2020-10-13 04:59 UTC, merged